export const menu = [
  {
    category: "Starters",
    name: "JASS Bourbon Wings",
    price: 10,
    description: "Rich, sweet bourbon flavour, baked to crispy perfection.",
    image: "JASS Bourbon Wings.jpg",
  },
  {
    category: "Starters",
    name: "Truffle Baked Oyster",
    price: 12,
    description: "Delicate oysters with the earthy richness of truffle.",
    image: "Truffle Baked Oyster.jpg",
  },
  {
    category: "Starters",
    name: "Pork Sisig Nachos",
    price: 9,
    description:
      "A Filipino-inspired favourite: tangy, spicy and full of crunch.",
    image: "Pork Sisig Nachos.jpg",
  },
  {
    category: "Main course",
    name: "Pineapple Nachos Pizza",
    price: 14,
    description: "A playful balance of sweet pineapple and savoury richness.",
    image: "Pineapple Nachos Pizza.jpg",
  },
  {
    category: "Main course",
    name: "Crispy Fish Chicken Sisig",
    price: 13,
    description:
      "Bold flavours and crispy textures, inspired by a Filipino classic.",
    image: "Crispy Fish Chicken Sisig.jpg",
  },
  {
    category: "Main course",
    name: "Beef Quesadilla",
    price: 11,
    description: "A golden quesadilla with a rich, cheesy beef filling.",
    image: "Beef Quesadilla.jpg",
  },
  {
    category: "Main course",
    name: "Pork Quesadilla",
    price: 10,
    description: "Crisp on the outside, with a warm, cheesy pork filling.",
    image: "Beef Quesadilla.jpg",
  },
  {
    category: "Main course",
    name: "Spicy JASS Burger",
    price: 12,
    description: "A well-seasoned burger with a satisfying kick of heat.",
    image: "Spicy JASS Burger.jpg",
  },
  {
    category: "Main course",
    name: "Cheese Pizza",
    price: 16,
    description: "A rich blend of cheeses, bubbling over a golden crust.",
    image: "Cheese Pizza.jpg",
  },
  {
    category: "Main course",
    name: "Buffalo Waffles",
    price: 9,
    description: "Crispy waffles meet bold, classic buffalo flavour.",
    image: "Buffalo Waffles.jpg",
  },
  {
    category: "Desserts & drinks",
    name: "Chocolate Lava Cake",
    price: 8,
    description: "Warm chocolate cake with a soft, molten centre.",
    image: "Buffalo Waffles.jpg",
  },
  {
    category: "Desserts & drinks",
    name: "Caramel Cheesecake",
    price: 7,
    description: "Creamy cheesecake with a buttery caramel finish.",
    image: "Buffalo Waffles.jpg",
  },
  {
    category: "Desserts & drinks",
    name: "Tropical Mocktail",
    price: 6,
    description: "Bright citrus and pineapple with a refreshing hint of mint.",
    image: "Pop Soda and Dragon Cocktails.jpg",
  },
  {
    category: "Desserts & drinks",
    name: "Iced Coffee Delight",
    price: 5,
    description: "Smooth cold coffee with cream and a touch of vanilla.",
    image: "Pop Soda and Dragon Cocktails.jpg",
  },
  {
    category: "Desserts & drinks",
    name: "Pop Soda & Dragon Cocktails",
    price: 7,
    description:
      "Colourful blends with tropical brightness and natural sweetness.",
    image: "Pop Soda and Dragon Cocktails.jpg",
  },
];
